### ISSUE TITLE
Can't kekulize mol

### ISSUE THREAD

**Issue by jlaw9** [NREL/rlmolecule#61]
In a recent QED optimization run, one of the MCTS jobs ran into this rdkit error:
```
Can't kekulize mol.  Unkekulized atoms: 18 21 29
```
Whis resulted in this downstream error:
```
Traceback (most recent call last):
  File "optimize_qed.py", line 163, in <module>
    run_games(run_config)
  File "optimize_qed.py", line 107, in run_games
    num_mcts_samples=config.get('num_mcts_samples',50)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/alphazero/alphazero.py", line 97, in run
    path, reward = MCTS.run(self, *args, **kwargs)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/mcts/mcts.py", line 66, in run
    self.sample(vertex, num_mcts_samples)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/mcts/mcts.py", line 86, in sample
    value = self._evaluate(search_path)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/alphazero/alphazero.py", line 72, in _evaluate
    self._expand(leaf)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/mcts/mcts.py", line 122, in _expand
    leaf.children = [self.get_vertex_for_state(state) for state in leaf.state.get_next_actions()]
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/molecule_state.py", line 59, in get_next_actions
    result.extend((MoleculeState(molecule, self.builder) for molecule in self.builder(self.molecule)))
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/molecule_state.py", line 59, in <genexpr>
    result.extend((MoleculeState(molecule, self.builder) for molecule in self.builder(self.molecule)))
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/builder.py", line 62, in __call__
    yield from inputs
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/builder.py", line 71, in __call__
    for molecule in inputs:
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/builder.py", line 71, in __call__
    for molecule in inputs:
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/builder.py", line 72, in __call__
    yield from self.call(molecule)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/builder.py", line 81, in call
    if self.filter(molecule):
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/builder.py", line 185, in filter
    return check_all_filters(molecule)
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/gdb_filters.py", line 68, in check_all_filters
    if fn(mol):
  File "/home/jlaw/projects/arpa-e/rlmolecule_branch/rlmolecule/molecule/builder/gdb_filters.py", line 10, in h2
    return mol.HasSubstructMatch(rdkit.Chem.MolFromSmarts('[R2r3,r4]([R1r3,r4])([R1r3,r4])[R1r3,r4]'))
AttributeError: 'NoneType' object has no attribute 'HasSubstructMatch'
```

I don't have the molecule that produced this error, and I'm also not sure how to reproduce it.

For now I think we can probably just skip molecules that produce this type of error.

**Comment by pstjohn** [comment]
hopefully addressed by #62
